import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/customs/common/UserLayout/Header";
import Footer from "@/components/customs/common/UserLayout/Footer";
import StoreProvider from "./StoreProvider";
import ScrollHandler from "@/components/customs/common/SmoothScrollProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollHandler />
        <StoreProvider>
          <Header />
            <div className="flex flex-col min-h-screen gap-40">{children}</div>
          <Footer />
          <Toaster richColors closeButton />
        </StoreProvider>
      </body>
    </html>
  );
}
